name: "CI"

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Check Build
        run: npm run build
        env:
          PERFSEE_TOKEN: ${{ secrets.PERFSEE_TOKEN }}
